import Head from "next/head";
import Link from "next/link";
import Nav from "../components/navbar";
import Heed from "../components/header";
import Footer from "../components/footer";


export default function Home() {





  return (
    <>
      <Head>
        <title>Legal-help || Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen bg-slate-950  overflow-x-hidden">
      <Nav />
      <Heed />
      <Footer />
      </main>
    </>
  );
}
